#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct cell {
    bool alive;
} cell_t;

typedef struct game_board {
    cell_t** cells;
    int size_x;
    int size_y;
} game_board_t;

game_board_t* NewGameBoard(int size_x, int size_y) {

    game_board_t* board = (game_board_t*) malloc(sizeof(game_board_t));

    board->size_x = size_x;
    board->size_y = size_y;
    board->cells = malloc(board->size_x * sizeof(*board->cells));

    // Allocate a sub-pointer inside the double pointer.
    for(int i = 0; i < board->size_x; i++) {
        board->cells[i] = malloc(board->size_y * sizeof(board->cells[0]));
    }

    // Mark all cells as dead to begin with.
    for(int i = 0; i < board->size_x; i++) {
        for(int j = 0; j < board->size_y; j++) {
            board->cells[i][j].alive = false;
        }
    }

    return board;
}

void CleanupGameBoard(game_board_t* board) {

    // Check if board exists before deallocating.
    if(board == NULL) {
        return;
    }

    // Free each sub-pointer inside the double pointer.
    for(int i = 0; i < board->size_x; i++) {
        free(board->cells[i]);
    }

    free(board);
}

void WritePPM(game_board_t* board, const char* file_name) {

    FILE* image_file;

    image_file = fopen(file_name, "wb");

    fprintf(image_file, "P6\n");
    fprintf(image_file, "# File generated by simplelife.\n");
    fprintf(image_file, "%d %d\n", board->size_x, board->size_y);
    fprintf(image_file, "255\n");

    for(int i = 0; i < board->size_x; i++) {
        for(int j = 0; j < board->size_y; j++) {
            if(board->cells[i][j].alive == true) {
                // Black for alive.
                fputc(0, image_file); // R
                fputc(0, image_file); // G
                fputc(0, image_file); // B
            } else {
                // White for dead.
                fputc(255, image_file); // R
                fputc(255, image_file); // G
                fputc(255, image_file); // B
            }
        }
    }

    fclose(image_file);
}

int main(int argc, char** argv) {

    // Seed RNG with time.
    time_t t;
    srand(time(&t));

    game_board_t* board = NewGameBoard(256, 256);

    // Fill the gameboard with random data.
    for(int i = 0; i < board->size_x; i++) {
        for(int j = 0; j < board->size_y; j++) {
            board->cells[i][j].alive = rand() % 2;
        }
    }

    WritePPM(board, "initial.ppm");

    CleanupGameBoard(board);

    return 0;
}